### ISSUE TITLE
Thank You + Feature Request: Select Active Word ...

### ISSUE THREAD

**Issue by FelipeRearden** [TfTHacker/obsidian42-text-transporter#1]
Hello @TfTHacker !!!!

I just watched your Demo video and I’m thrilled ! 

Since I’m a keyboard lover, this plugin is gonna be a game changer for my workflow. Thank you so much for your hard work to bring this features to our community !!!!!

I follow you on twitter too and I wanna take this FR as an opportunity to say thank you for sharing your knowledge with us. 

My Feature Request is based on the beginning of your `Demo` when you showed powerful hotkeys to deal you `Select Current Line` 
- Select Current Line
- Select Current Line and expand up into previous block
- Select Current Line and expand up into next block

Is it feasible to do the same feature to the `current word` ?
- Select Current Word 
- Select Current Word and expand up into previous word
- Select Current Word and expand down into next word

**_I’m excited about this: Keep pressing the hotkey for Select Current Word selects the next word_**

### My Ideia for this FR

Since I use emphasize text a lot (bold, italic, highlight, <u></u> and some customizable tags) would be much more pleasant to use this hotkey instead of `shift+arrows` to select words then apply the decoration.
- I think I’m gonna use `shift+right arrow` and `shift+left arrow` as hotkeys for this new commands :)

---

Thank you for your reading this and for your time.  I hope you like my suggestion :)
- Let me know if you need more information

I wish you a fantastic day!

**Comment by TfTHacker** [comment]
Thank you for your kind words and feedback. Regarding selecting word, you are looking for a way to assign this yourself to a custom keyboard, since it can kind of be doing with CTRL+SHIFT+ARROW (on windows)?

**Comment by FelipeRearden** [comment]
Hello @TfTHacker !!!

Thanks for the reply. 

Sorry for my mistake: I thought this hotkey feature wasn’t available on MacOS but I read your reply and did a test on MacOS and `Shift+Option+Arrow` is the way to do this on MacOS
- Regarding to hotkeys, next time I will make a test before writing a FR :)

Would amazing to have the freedom to assign to a custom keyboard, but I think there are so much more important features to be developed  (#3 And #2)  to this fantastic plugin that I think we should close this issue for this moment. 

This weekend I will  use the beta release and I hope I could bring some valuable insights to make this plugin even more powerful to our community. 

Sorry again for the mistake and thank for your reply!

Have a great day!

**Comment by TfTHacker** [comment]
No need to apologize. I really appreciated hearing from you and keep feedback coming.

I am working on an update that I will push out by end of day. Significantly faster file handling and also a new feature or two. So that might interest you if you will be testing.

**Comment by FelipeRearden** [comment]
Thank for the information. This is amazing!

Deal! I will wait for the next release to start my test :)

Thanks again @TfTHacker !
