### ISSUE TITLE
[Bug] `ABI` Command vs `CC` Command (Release 0.7.0)

### ISSUE THREAD

**Issue by FelipeRearden** [TfTHacker/obsidian42-text-transporter#12]
Hello @TfTHacker !!!

I think I find a bug: the `ABI` command have the same result as `CC` 

If I understood correctly the definition of CC and ABI:
- CC -> `![[Filename#^BlockRef]]` (embed link)
- ABI -> `[[Filename#^BlockRef]]` (not embed link)

On 0.7.0 we have CC and ABI as `![[Filename#BlockRef]]` for both commands.

Sorry if I understood incorrectly the commands.

Have a great day!

**Comment by TfTHacker** [comment]
You are right. These commands are redundant, basically doing the same thing. I will reduce it to one command in the next release. Thank you for the feedback on this.

**Comment by FelipeRearden** [comment]
@TfTHacker,

 We need these two commands working as I described above. 
- One for embed links `CC`
- Another for block references `ABI` 

Please don't kill one of then :)

**Comment by TfTHacker** [comment]
For me they are both doing block embeds. So you are suggestion block embed and just block ref?

**Comment by FelipeRearden** [comment]
Yes :) 

One for embed links `CC` ![[Filename#^BlockRef]]
Another for block references `ABI` [[Filename#^BlockRef]]

**Comment by FelipeRearden** [comment]
Hello @TfTHacker 

I’m starting my tests on 0.8 right now !!!

I have a question:
> Consolidated commands CC and ABI into one. (Thanks FelipeRearden ). Will expand on this command as per your issue.

I’m not a native English speaker and I’m sorry if I didn’t understood correctly ->  is `ABI` coming back in the next/future release as a new feature: `[[Filename#^BlockRef]]`?
- `CC` `CA` and `ABI` closes the types of `[[ ]]` references possible in Obsidian; 
- and I’m asking because I’m updating the text I’m writing about Transporter Commands (that I will post as a new Discussion in the next ours) and `ABI` has a  role the commands that I will suggest to you and our friends.
 
Have a great day!

**Comment by TfTHacker** [comment]
Basically the old copy as block reference and add block reference were doing the same thing. Just the first command only worked on one block, while the other did multiple blocks. So it was redundant. They both insert block embeds ( using the ! In the front). This command supports not just block embeds of paragraphs, but block embeds of headings. So lets day you highlight this text:
```
# heading 1
Paragraph 1

Paragraph 2
```
It will be converted too
```
# heading 1
Paragraph 1 ^ab3affa

Paragraph 2 ^zadfa9a
```

Amd the clipboard will now contain:n

![[file name#heading 1]]
![[file name#^ab3affa]]
![[file name#^zadfa9a]]


History: I wrote the first command in the beginning, then a second command to do multiple paragraphs. I didn’t realize they are basically doing the same thing. This is why I reduced it to one command. But they always output block embeds with !, not block references without.

**Comment by TfTHacker** [comment]
And thank you for your help :-)

**Comment by FelipeRearden** [comment]
Thanks for you reply!

I will update my suggestion.
