### ISSUE TITLE
Embed More than One Block

### ISSUE THREAD

**Issue by BrianBarry** [TfTHacker/obsidian42-text-transporter#18]
If I select two blocks and then the command:

Copy block embed as an alias

only the last block selected is copied. Is that intended?

**Comment by TfTHacker** [comment]
The alias command doesn’t currently support multiple blocks. Do you think it should?

**Comment by BrianBarry** [comment]
For outlines it pretty important. Say..

- Block A
	- a1
	- a2

As things now stand you only get a2.

**Comment by TfTHacker** [comment]
The newest beta release now supports generating aliases across multiple blocks.
