### ISSUE TITLE
a bunch of feedback on the beta

### ISSUE THREAD

**Issue by chrisgrieser** [TfTHacker/obsidian42-text-transporter#2]
Here a bunch of smaller issues I discovered while testing

feature feedback
- the "all commands" commands is a great idea, some other plugins would benefit from doing something like this
- I am not sure what the usecase for "select previous block" would be, when you already have "select current block" and "expand to previous/next block"? If there is no usecase, you could maybe ditch those to reduce the number of commands?
- I do not really like the implementation of the pull/push/copy commands. Selecting a note, selecting a beginning line, selecting an ending line... It feels a bit tedious, and I got the impression that working with copy/cut-paste and two panes would be quicker than doing it with this plugin. The "bookmarks" setting is a nice solution to speed up the selection of a note – maybe you could just use a value defined in the options (top of the file, bottom of the file, etc) to skip the selection of beginning/ending lines and so on? Like I press only one hotkey, select out of my 5 bookmarked notes, and the current line gets simply appended/prepended.
- I get that bookmark+`TOP`/ `BOTTOM` does something similar, but I believe it feels a bit counterintuitive. And also means that until you use the plugin with some bookmarks, it would feel tedious. I dunno. Maybe just having a list of *all* lines is a bit too much, and having TOP/BOTTOM/Headers as options would reduce the tediousness a bit?

wording
- "copy block as block as block reference" is phrased a bit weird.  I'd expect sth like "Copy embedded block reference"?
- is there a reason it is called "select current *line*", but also "select next *block*"? Confuses me a bit, since I'd expect something like "next line" and "current block" as well then. (I never really understood the difference between lines and blocks in Obsidian, tbh.)
- it only becomes clear upon testing that "copy block as block as block reference" and "Add block ref ID's to selection and Copy them to clipboard" do the same thing. Maybe it could also be phrased as "line/selection" as the other commands?
- I think the "Alias Indicator" in the settings should rather be called "Alias Placeholder", if I am not misunderstanding the feature?
- is it necessary to add `;` to the end of every bookmark line, when not using TOP/BOTTOM/Heading? (add some info on that?)

Otherwise, as far as I can tell from testing this plugin a bit, I didn't encounter any bugs. (But I also could not test all features, since I do not use daily notes, for example.)

**Comment by TfTHacker** [comment]
Awesome Awesome! Thank you so much for your help with testing and feedback. I agree, some aspects of the navigation feel tedious. I will do some experimenting on the flow. It is so hard to figure out the right balance of being fast, and having precision control.

will also improve the wording based on your feedback.

**Comment by TfTHacker** [comment]
Just to mention, “ is it necessary to add ; to the end of every bookmark line, when not usingTOP/BOTTOM/Heading? (add some info on that?)” 

you don’t need to use the semi-colon in this case. I will update the description.

**Comment by TfTHacker** [comment]
I think I have tweaked some of these issues in an upcoming release. Others might wait while we do more experiments with the flow of the tool.
