### ISSUE TITLE
Text Transporter Commands

### ISSUE THREAD

**Issue by BrianBarry** [TfTHacker/obsidian42-text-transporter#20]
I'm obviously confusing myself with the number of options that your plugin offers - and my attempt to translate them into what I'm used to seeing in Roam. My latest issue is with accessing the commands themselves with the Command Menu. The first screenshot displays what I see when I look for "text" and the second what is displayed with the All Commands option. Is that the intended functionality?

![Screen Shot 2021-09-20 at 8 39AM](https://user-images.githubusercontent.com/43768551/134031914-881d82d3-fb9d-49e9-a31e-13bb675288ca.png)

![Screen Shot 2021-09-20 at 8 39AM 1](https://user-images.githubusercontent.com/43768551/134031937-c40a9b1a-d821-43d8-b491-35630a121914.png)

**Comment by TfTHacker** [comment]
There should be more commands for sure. Here is a screenshot of what I have:

![image](https://user-images.githubusercontent.com/69121180/134058318-3b9e1183-0ca6-4516-8119-d06ada1825eb.png)

When editing a file, when you right mouse click to you see additional commands?

**Comment by BrianBarry** [comment]
I do see the additional commands when right-clicking when editing a file. 

There is a menu option to:

- Send link of current note to a file

Once that is done, the command:

- Replace link with text and alias 

does exactly what I’m trying to do. But, not with the entire file — only with a selection of blocks. 

Brian

**Comment by TfTHacker** [comment]
Brian,
I am sorry, I still don't understand what you are asking.

**Comment by BrianBarry** [comment]
Sorry to not describe things clearly. Maybe it is better to revert to Roam-speak. In Roam, you can select several blocks, get their block references, copy the references to another page and then convert them all to text and alias. 

Once you do that you get an editable version on the new page, with a minimal (*) link back to the original. 

As I understand the new version, you can now move several blocks to a new file as embeds. You can then convert those embeds to text and alias. But, when you do, you still see the "long" embed in edit mode and a "clean" version of the blocks is available only in preview mode - where you can't edit them. 

And, you have to convert blocks to text and edit mode one at a time. 

I'm really asking for the same functionality that is in Roam - although I am obviously not very good at describing it.
