### ISSUE TITLE
Bookmark not recognized

### ISSUE THREAD

**Issue by BrianBarry** [TfTHacker/obsidian42-text-transporter#26]
I've tried various ways to describe a file - I.e., how much of a path to provide, but I'm not having much luck. I'm attaching two screenshots - the first shows my current attempt at describing a bookmark for the file scratchpad.md. The second shows the files that are presented when using Quick Capture. How should I describe this file so that the Bookmark feature recognizes it as a Bookmark? 

![Screen Shot 2021-09-27 at 1 01PM](https://user-images.githubusercontent.com/43768551/134977756-fdc1c91a-29dc-4833-809b-3a304e76a346.png)

![Screen Shot 2021-09-27 at 1 11PM](https://user-images.githubusercontent.com/43768551/134978211-cb282438-b978-470d-b90d-a7ccd1983890.png)

**Comment by TfTHacker** [comment]
I think there should be no space after ;

**Comment by BrianBarry** [comment]
I’ve tried it both ways. Same result. The space works after the DNPTODAY version.

**Comment by TfTHacker** [comment]
For sure there should be no space after the semicolon. So:

DNPTODAY;BOTTOM

I just tested and this is working in my vault. So no spaces at all on the line.

**Comment by BrianBarry** [comment]
I tried it like this:

My Vault/Scratchpad.md;BOTTOM
DNPTODAY; BOTTOM

The DNPTODAY bookmark works. The Scratchpad.md does not. 

The DNPTODAY has a space, the Scratchpad.md does not. 

Brian

**Comment by BrianBarry** [comment]
Got it working. 

The version that works for me has the folder name followed by the filename. The BOTTOM parameter works with or without a space. 

If I extend the path to include the vault name the bookmark is not recognized. 

This works:

Incoming Ideas/Scratchpad.md; BOTTOM

This does not: 

My Vault/Incoming Ideas/Scratchpad.md; BOTTOM

with or without a space following the semi-colon. 

Brian

**Comment by BrianBarry** [comment]
This works great with the two options TOP and BOTTOM. Could not make it work by placing the cursor under a header and specifying that the new entry should be made there - either TOP or BOTTOM of “there.” 

I don’t understand the meaning of the second and fourth option shown in the screenshot — when I select them they do not seem to control the location of the entry based on the cursor location when first starting the Add Bookmark process. 

Use Case: If I could control where on a file the entry went, I would use this with Projects to place newly added supplementary information (i.e., not tasks) immediately below the “Other Information” header in the project file.

**Comment by TfTHacker** [comment]
So to place it to a specific line it is looking for a unique line in the file. So if you have:

# Inbox

And text will come into this location under it, you would add:

filename.md;# Inbox

You can get this bookmark to appear in the context menu (when you right mouse click on a line) by adding a * to beginning:

*filename.md;# Inbox

Or:

*filename.md;TOP

For creating a context menu shortcut to the top of that file.

I will do a video soon since its hard to explain in message format.

**Comment by BrianBarry** [comment]
I got it working. 

Thanks! Very powerful plugin.

**Comment by TfTHacker** [comment]
Awesome!
