### ISSUE TITLE
Cant Append Quick Capture to a note 

### ISSUE THREAD

**Issue by skillhacker-code** [TfTHacker/obsidian42-text-transporter#28]
Please provide an option to append the quick capture note the end of the note . 

now only option available is to prepend ie to the capture the note to the top of the file 

Thank you so much 

The plugin is so useful

**Comment by TfTHacker** [comment]
this can be done. You can scroll to the bottom of the file when the file contents appears in the suggester. Or, if you are at the very top of the file in the suggester, press up arrow key and it will wrap around to the bottom in the suggester.

Additionally you can look into bookmarks for creating predefined locations in your vault for quickly adding text to those predefined locations. More info: [Bookmarks](https://github.com/TfTHacker/obsidian42-text-transporter/blob/main/README-Bookmarks.md)

**Comment by skillhacker-code** [comment]
Thank you so much,

**Comment by ooloth** [comment]
> You can scroll to the bottom of the file when the file contents appears in the suggester. Or, if you are at the very top of the file in the suggester, press up arrow key and it will wrap around to the bottom in the suggester.

@TfTHacker In my experience, line 99 is the highest that appears when doing this, even if the file is longer. I can start guessing at how high the line numbers go, but I'm doing so in the dark. Any tips for quickly identifying the last line of a long file with this approach? 

Or ideally, just appending to the file by default without having to choose the last line of the file?
