### ISSUE TITLE
Suggestion: More Consistent Command Names

### ISSUE THREAD

**Issue by chrisgrieser** [TfTHacker/obsidian42-text-transporter#38]
I think the two `send` commands and the two `push` basically do the same thing, don't they?

If I am not wrong, then I'd suggest to name all for of them `Push` for consistency.

<img width=50% alt="Screenshot 2021-11-01 23 05 03" src="https://user-images.githubusercontent.com/73286100/139748264-68c420e7-f8b2-4f70-9c49-3ab6e068fa37.png">

---

Furthermore, in one case it's "Send to clipboard", while in another two it's "copy". These, too, could be named consistently. (Slight overlap with the point above for the last command.)

<img width=50% alt="Screenshot 2021-11-01 23 07 12" src="https://user-images.githubusercontent.com/73286100/139748451-a138c516-5ef2-434d-9231-f4ecb749f2ab.png">
<img width=50% alt="Screenshot 2021-11-01 23 08 36" src="https://user-images.githubusercontent.com/73286100/139748521-dcfd5c0d-9b35-491b-b266-447686b477c4.png">

**Comment by TfTHacker** [comment]
I agree that it is not clear. The send command is used for sending a link to the file itself, like [[file name]], and the copy commands are for blocks [[file name$^afasbasd]].

I agree that better names should have been chosen, but now that the plugin has been in use for two years, many have adapted to their names. So, for now, I am going to leave them as they are, but I will try to make sure I choose better names for new commands.

Sorry I didn't respond to this great suggestion back then :-)
