### ISSUE TITLE
⌘+L only works for current line

### ISSUE THREAD

**Issue by DutchPete** [TfTHacker/obsidian42-text-transporter#5]
I have assigned hotkey ⌘+L to *select current line*. In the video you say that if you keep pressing ⌘+L it will keep selecting successive lines, but that does not work. ⌘+L only works for the current line, repressing the hotkey does not do anything.

Am I missing something?

**Comment by TfTHacker** [comment]
Actually assign it to “Select current line and expand into next block”.

Looking forward to more feedback.
