### ISSUE TITLE
Live Preview support

### ISSUE THREAD

**Issue by DutchPete** [TfTHacker/obsidian42-text-transporter#50]
Is it possible to amend the plug-in so it supports Live Preview?

**Comment by DutchPete** [comment]
Any news on this?

**Comment by TfTHacker** [comment]
Is there a specific feature not working for you?

**Comment by DutchPete** [comment]
I used to be able to select multiple text blocks, right-click, *Copy block embeds from this selection*, then paste them into another note as transclusions. However, now it just takes 1 block out of the total selection.

Another thing I have noticed is that when I do that right-click, the selection is undone, whereas before (when the was no LP) all the blocks remained selected when right-clicked.

**Comment by TfTHacker** [comment]
Are you on the insider build it public build?

**Comment by DutchPete** [comment]
Insider

**Comment by TfTHacker** [comment]
Can you record a quick video for me? This is working for me on both my windows machine and ipad.

**Comment by DutchPete** [comment]
I am not too good at this kind of thing. I did make a vid, but the smallest size I got is 17.3 MB :-(
So, since I could not paste it here (max. = 10 MB) I up;oaded it to Imgur. Here is the [direct link](﻿https://i.imgur.com/mg0Q6g7.mp4﻿).

I hope you can see that of the 3 paragraphs I selected (*Copy block embed from this selection*), then tried to paste, only 1 was pasted.

**Comment by DutchPete** [comment]
Is the video quality good enough?

**Comment by TfTHacker** [comment]
I want to apologize for the delay. Swamped at work. The video is clear that its not working on your device. But I have to tell you I can't duplicate it. This feature is working just fine for me. This is silly, but can you try it with another theme?

The other thing would be to disable all other plugins and just leave text transporter on.

**Comment by DutchPete** [comment]
Thanks for replying, I understand your time constraint.

I tried the plug-in in the Help vault, and it does not work either. So, something appears to be wrong at my end. I'll have to figure it out myself.

I'll close this issue.
