### ISSUE TITLE
404 on bookmarks link

### ISSUE THREAD

**Issue by notuntoward** [TfTHacker/obsidian42-text-transporter#75]
In the obsidian settings for Text Transporter, there's this link:

![image](https://github.com/TfTHacker/obsidian42-text-transporter/assets/3851891/9d348002-6a1f-40bb-a084-a384d5aa56ae)

When I click on it, I get a 404 page not found error

**Comment by TfTHacker** [comment]
This will be fixed in the next release. Thank you for reporting it.
