### ISSUE TITLE
Pasting copy block as alias moves cursor to new line

### ISSUE THREAD

**Issue by harpreetchima** [TfTHacker/obsidian42-text-transporter#80]
When you paste after using the Copy Block as Alias hotkey, it will insert the asterisk but also move the cursor to the next line.

https://github.com/TfTHacker/obsidian42-text-transporter/assets/46920506/70baa9b4-cc51-4d6e-b449-43d33aa57545

**Comment by TfTHacker** [comment]
Hi. Thank you for the feedback. I just reviewed the code history, and this has been the default behavior for about three years. Therefore, I won't be making any changes, as others have become accustomed to the function working this way.
