### ISSUE TITLE
Stopped working - Push line/selection to another file (PLT)

### ISSUE THREAD

**Issue by PJJPtx** [TfTHacker/obsidian42-text-transporter#81]
This recently stopped working for me.
However, "Send link of current note to the Clipboard (SLC)" does work. It seems it's just the commands that write to a bookmarked file.

**Comment by TfTHacker** [comment]
Thank you for reporting this. I have recently pushed out an update and this might be due to that. Can you send me a screenshot of your bookmarks (block out anything private) and let me know the path that is not working.

Is it any bookmark path? is it any command pushing to a bookmark?

**Comment by brsma** [comment]
While PLT generally still does what it should, specifically the DNP* bookmark paths stopped working for me with the last update. :-( Perhaps it's the same issue. Seems like the bookmark shorthand does not get resolved anymore:

Console: `Uncaught (in promise) Error: ENOENT: no such file or directory, open '/Users/brsma/Obsidian Sync/Notes/DNPTODAY;## Notes' (plugin:obsidian42-text-transporter:1181)` 

![image](https://github.com/TfTHacker/obsidian42-text-transporter/assets/8915/2cbf176b-9d83-423a-8ff8-a2caf57db942)

**Comment by brsma** [comment]
Update: Only seems a problem with PLT. Opening the DNP* bookmarks with (BO) works.

**Comment by TfTHacker** [comment]
I am pushing out a fix for this. please test it and let me know if it is working.

Release: 1.0.11

**Comment by brsma** [comment]
Fixed 🙌

**Comment by PJJPtx** [comment]
Thank you for your quick fix!
